/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://yr4tlzuhcvcnhlxopdfnio5w4y.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jwonuabmlba2zmu7vwp3eqt7zq",
    "aws_cloud_logic_custom": [
        {
            "name": "api54bd992e",
            "endpoint": "https://o9sfl0ia7k.execute-api.us-east-2.amazonaws.com/staging",
            "region": "us-east-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-2:aff33acf-77e9-4b5b-b05a-d88ca14af959",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_optq4ucOa",
    "aws_user_pools_web_client_id": "2ua7fpf6q7g5f95ssttrnq9gbd",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME",
        "PHONE_NUMBER",
        "BIRTHDATE"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "arbai17e4f0fa728943eb98d6e551b5fca0e131646-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
